# Generated by Django 4.2.2 on 2023-07-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
